project:
  type: book

book:
  title: "thesis"
  author: "Morteza Ansarinia"
  date: "11/28/2022"
  chapters:
    - index.qmd
    - chapters/acknowledgements.qmd
    - chapters/abstract.qmd
    - chapters/introduction.qmd
    - chapters/references.qmd
    - chapters/conclusion.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: report
    toc: true
    geometry:
      - left=3cm
      - right=2cm
      - top=2cm
      - bottom=2cm
    include-in-header: 
      text: |
        \usepackage{ragged2e}
