project:
  type: book

book:
  title: "Towards a Computational Model of General Cognitive Control Using Artificial Intelligence, Experimental Psychology and Cognitive Neuroscience"
  author: "Morteza Ansarinia"
  date: last-modified
  chapters:
    - index.qmd
    - chapters/abstract.qmd
    - chapters/0_introduction.qmd
    - chapters/6_discussion.qmd
    - chapters/references.qmd
  appendices:
    - appendices/appendix_a.qmd
    - appendices/appendix_b.qmd
    - appendices/appendix_c.qmd
    - appendices/appendix_d.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: report
    fontsize: 12pt
    papersize: a4paper
    linestretch: 2
    toc: true
    lof: true
    lot: true
    geometry:
      - left=3cm
      - right=2cm
      - top=2cm
      - bottom=2cm
    include-in-header: 
      text: |
        \usepackage{ragged2e}
