project:
  type: book
  # execute-dir: project

book:
  title: "Towards a Computational Model of General Cognitive Control Using Artificial Intelligence, Experimental Psychology and Cognitive Neuroscience"
  author: "Morteza Ansarinia"
  date: last-modified
  chapters:
    - index.qmd
    - chapters/abstract.qmd
    - chapters/0_introduction.qmd
    - articles/1_cogtext.qmd
    - articles/2_cogenv.qmd
    - articles/4_oxfordch.qmd
    - articles/5_acnets.qmd
    - chapters/6_discussion.qmd
    - chapters/7_references.qmd
  appendices:
    - articles/8_nback.qmd
    - articles/9_behaverse.qmd
    - articles/10_seqgen.qmd
    - appendices/11_projects.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: report
    fontsize: 12pt
    papersize: a4paper
    # linestretch: 1
    toc: false
    lof: false
    lot: false
    geometry:
      - left=3cm
      - right=2cm
      - top=2cm
      - bottom=2cm

    include-in-header: 
      - text: |
          \usepackage{ragged2e}
          \usepackage{setspace}
          \usepackage{colortbl}
          \doublespacing
          \usepackage{sectsty}
          \allsectionsfont{\singlespacing}
