name: thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - notebook
  - ipykernel
  # - quarto  # not working yet with tinytex, install it manually
  - R
  - r-jsonlite
  - r-rmarkdown
  - r-readxl
