# General Discussion

#### On the importance of cognitive control research {.unnumbered}
Psychology is tasked to make sense of what humans do, and what humans do depends on what happens in their immediate environment [@miller1960]. One ability that is of utmost importance to human functioning is to exercise cognitive control which enables pursuing goals in a changing world, avoiding prepotent responses, and effectively generalizing prior experiences to new situations. Due to its ubiquitous presence in everything we do, cognitive control plays a crucial role in our daily lives, long-term achievements, and health. Accordingly, the possibility to enhance cognitive control in a way that transfers to real life situations could have important implications.

Progress towards developing effective cognitive control training programs is however limited by the lack of a formal, quantitative definition of cognitive control. The main challenges that this thesis aims to address are (a) to gain greater clarity on the cognitive control constructs (what it is and how to measure it), and (b) to understand what features of the cognitive system (i.e., the agent) and what features of the task (i.e., the environment) determine cognitive control, its functioning, and generalization.

#### On the importance of a multidisciplinary view of cognitive control {.unnumbered}
To address these challenges, this thesis relies on the multidisciplinary synergy within cognitive sciences, primarily between artificial intelligence, psychology, and cognitive neuroscience. This synergy is apparent at several levels. First, we apply artificial intelligence techniques as mere tools in our toolbox to interpret human data. In this sense, modern machine learning models provide new insights on human cognition as they are applied to behavioral data,  scientific documents, and neuroimaging data. Second, a richer form of interdisciplinary synergy to build bridges between disciplines to develop new computational models that instantiate cognitive control and generalizes across tasks, furthering our understanding of cognitive control in humans.

## Defining cognitive control
#### On the importance to define and quantifiy cognitive control {.unnumbered}
Concepts that capture higher-order cognitive abilities such as cognitive control are difficult to define—and consequently to quantify. To understand those cognitive abilities, previous research has devised a variety of theoretical constructs and cognitive tasks, the relationships between which are not always clear. Chapter 1 (CogText) is an attempt to quantitatively assess this lack of a cohesive understanding by using recent advances in artificial intelligence. More specifically, we performed a large-scale text analysis to create a knowledge graph that relates theoretical constructs and empirical tasks about cognitive control. The rationale of this analysis is that constructs are related to the extent they are assessed using a similar set of cognitive tasks and cognitive tasks are related to the extent they are thought to involve similar cognitive constructs. As expected, the knowledge graph confirms the complex nature of cognitive control and illustrates two specific phenomena that may explain the difficulty of defining cognitive control: task impurity (tasks measuring multiple constructs) and construct hypernomy (multiple ways of defining and measuring constructs). These results have several implications for the study of cognitive control. First, greater theoretical clarity is needed on cognitive control—this may be achieved by adopting a more formal approach grounded in computational modeling. Second, there is currently no single task able to assess cognitive control, indicating a need for better environments for assessing it. This could entail, for instance, assessing cognitive skills using a battery of tasks (varying contexts and demands) or to develop better, perhaps more complex tasks (e.g., video games). Finally, because cognitive control is not associated with a single cognitive function but rather involves interactions with many cognitive functions in multiple tasks, it is likely that cognitive control is associated with a range of large-scale brain networks as opposed to a single brain area or network.

#### On the importance of an interoperable battery of tasks for humans and artificial agents (CogEnv)  {.unnumbered}
There have been significant advancements in both artificial intelligence and psychology, but they have not yet been fully integrated. This may be due to a lack of appreciation for their relevance, or the lack of tools to directly compare the behavior of humans and artificial agents. While there are many examples in the scientific literature of human behavior being compared to specific artificial agents, this type of comparison is typically done at the level of a single task, using a limited set of computational agents. Furthermore, these comparisons are not developed in a way that allows for reuse or extension.

To study cognitive control and other cognitive processes, it is necessary to be able to systematically compare the behavior of humans and artificial agents across multiple tasks. A tool that allows humans and artificial agents to perform the same set of tasks and directly compare their behavior would greatly benefit our understanding of cognitive control in both psychology and computer science.

To facilitate testing and integration of multidisciplinary theories in an interoperable environment, Chapter 2 provides a virtual environment called CogEnv. CogEnv lets both humans and artificial agents perform the same battery of cognitive tasks, providing data that can be directly compared in typical psychological experiments. As a proof of concept, we trained baseline RL agents to perform a battery of cognitive control tasks, and also collected human data for comparison. The overall framework is operational and appears promising. A preliminary investigation suggests that comparing the performance and error profiles of human versus baseline RL agents may reveal aspects of human cognitive control that have not yet been addressed by artificial agents.

#### On the importance of artificial models that act and functionally decouple control from the controlled act (CogPonder)  {.unnumbered}
The goal of CogEnv is to allow for the direct comparison of computational agents and humans performing exactly the same cognitive tasks and thus to promote more systematic progress in our understanding of  cognitive control. Yet, to make progress it is necessary to develop artificial agents that are capable of performing multiple tasks and which provide insights on cognitive control. To this end, in Chapter 3, we developed CogPonder, a computational framework for general cognitive control. . It is a flexible, differentiable end-to-end deep learning model that decouples the act of control from the controlled act and that can learn to perform the same cognitive tests that are used in cognitive psychology to test humans. 

The goal of CogEnv is to allow for the direct comparison of computational agents and humans performing the same cognitive tasks, thus promoting more systematic progress in our understanding of cognitive control. To achieve this goal, it is necessary to develop artificial agents that are capable of performing a battery of cognitive tasks while being constrained by computational requirements of cognitive control.

To this end, Chapter 3 presents CogPonder, a computational framework for general cognitive control. CogPonder is a flexible, differentiable end-to-end deep learning model that separates the act of control from the controlled act, and can be trained to perform the same cognitive tests used in cognitive psychology to test humans. We implemented an instance of CogPonder and trained it to perform two cognitive tasks, aligning its behavior with that of humans collected in a previous study. The results show that after training, CogPonder behaves similarly to humans across both tasks in terms of accuracy and response time distributions. These results demonstrate the potential of the CogPonder framework to provide interesting new insights and research opportunities for both psychology and computer science.

## Training and generalizing cognitive control

#### On the importance of cognitive training studies to study and test cognitive control {.unnumbered}

Research on the effects of complex tasks, such as video games, on cognitive training may benefit from and contribute to the proposed broad view of cognitive control. Chapter 4 reviews the literature on the effects of different genres of video games on cognition. Action video games, such as first- and third-person shooter games, are particularly interesting because they have been specifically associated with greater cognitive enhancement compared to other types of video games, such as puzzle or life-simulation games. The transfer effects of action video game playing to a range of cognitive tasks have been linked to improvements in reward processing, spatial navigation, and most notably for the context for this thesis, top-down attention and cognitive control.

This review highlights that cognitive training interventions using video games need to be endowed with specific game mechanics to generate cognitive benefits, potentially by enhancing cognitive control abilities. We discuss the potential game mechanics that could be used and call for more systematic research on the relationship between video game mechanics and cognition. We also note that as video games become more advanced and mix different genres and gameplay styles, it will become increasingly difficult to study and understand their effects on cognition. This article lays the foundation for the study of cognitive and brain functioning using video games and illustrates the value of this approach for investigating general cognitive control.

#### On the importance of studying brain function to understand cognitive control (ACNets)  {.unnumbered}
The study of differences in functional brain networks between action video game players and non-video game players can advance our understanding of the mechanisms underlying the training effects and the neural mechanisms supporting cognitive control in general. In Chapter 5, we show that it is possible to reliably classify new participants as habitual action video game players or non-video game players based on their resting-state functional connectivity. Furthermore, an analysis of the features that are most important for this classification accuracy reveals that what differentiates habitual video game players from non-video game players is not the connectivity within specialized functional brain networks, but rather the relationships between networks, supporting current theories of action video game training that attribute their benefits to domain-general abilities. The results also show that the most important inter-network relationships in this context involve control-related and sensorimotor networks, specifically the relationships between the cingulo-opercular and sensorimotor networks, and between fronto-parietal and sensorimotor networks.

These results suggest that action video game play may affect cognitive control, hence have important implications for the study of cognitive training. Furthermore, by demonstrating that resting-state data contains information related to action video gaming, these results suggest that resting-state data could be a valuable tool for studying cognitive training effects and their potential for transfer, potentially leading to the development of more effective cognitive training programs. Additionally, these results have practical value for cognitive scientists studying cognitive control, as results imply that action video game training may be a new tool for causally studying cognitive control.
 
## Future perspectives
There are a number of limitations to the approach outlined in this thesis. One major limitation is the scope of the proposed environment. For example, the current form of CogEnv ignores the real-time nature of most cognitive environments by providing a turn-based mechanism that suspends the environment until the agent finishes its computations and generates an action; a situation such as this is unlikely to occur in real life. Possible directions for addressing this limitation include extending the capabilities of CogEnv by establishing a larger library of computational models that can interface with the environment perhaps in real-time, such as CogPonder [or more broadly real-time reinforcement learning @ramstedt2019], and creating a more comprehensive set of cognitive tests [e.g., tests that are explored in @CogText or @Enkavi2019]. Additionally, there is potential for further refinement of the data processing and analysis pipelines, and the adoption of more standardized data formats that support multiple tasks and experimental designs [see for example Behaverse data model in @AppendixB].

Another area for future research could be the development of more realistic and ecologically valid cognitive tasks and experiments [cf. Discussion in @CogPonder and @ACNets], such as the use of video games or other rich and challenging environments, as well as the use of more complex and dynamic scenarios. By testing cognitive models in more realistic environments, we can better understand the limitations and capabilities of these models, and improve their performance. 

This may also require a more general computational account of cognitive control. By developing a computational model of cognitive control that is applicable to a wide range of tasks, we may be able to better understand and improve cognitive control in both humans and artificial agents. One particularly interesting approach involves the integration of artificial intelligence techniques into cognitive modeling. This could be facilitated by applying scalable machine learning (e.g., deep learning) to complex cognitive models, in order to create more accurate and comprehensive simulations of the human brain and mind. By testing sophisticated cognitive models at scale, we can better understand the limitations and capabilities of these models, and improve their ability to explain human phenomena.
Another useful approach consists of developing better taxonomies, concepts, and tasks—ideally via collaborative efforts of researchers in neuroscience, experimental psychology, and artificial intelligence—which may lead to more comprehensive and consistent models of cognitive functions. For example, psychologists can provide detailed ontologies of cognitive processes, while neuroscientists provide insights into the underlying brain mechanisms that support those processes, and computer scientists develop new algorithms and technologies for modeling and testing those processes.

A multidisciplinary synergy may also be achieved through direct comparisons of human and artificial agents. By using advanced artificial intelligence techniques, it is possible to create artificial agents that mimic human cognitive processes. By comparing the performance of these agents to human subjects on a variety of cognitive environments, we can better understand the similarities and differences between human and artificial cognition, and develop more accurate and comprehensive models of the human mind. By such a synergy, we can create a more comprehensive and integrated understanding of cognitive control and other cognitive functions.

The use of previously unexplored experimental techniques is another important direction for future research in cognitive control. In particular, the combination of functional magnetic resonance imaging (fMRI) and resting-state fMRI, along with the use of multitask batteries and interventional experimental designs, can provide valuable insights into the mechanisms of cognitive control (see Appendix XX for a study protocol that goes along these lines). Integrating task-driven and resting-state fMRI data has the potential to inform us about the neural basis of cognitive control, and this information can be used to develop scientific theories of cognitive control and identify potential neural markers of cognitive control abilities. By including multitask batteries to assess transfer effects, it is possible to determine how the brain enables the generalization of prior performance on one task to another. This information can help to understand the underlying mechanisms of cognitive control, and to develop theories about how cognitive control abilities are acquired and generalized, and why some interventions are successful while others are not.

## Conclusion
Taken together, the current work explores approaches from a variety of cognitive science disciplines that aim to better understand the concept of cognitive control. I presented cases in which neuroscience, experimental psychology, and artificial intelligence can collaborate to advance our understanding of cognitive control and the challenge of generalizing this capacity to new contexts (i.e., transfer effect). In the age of ubiquitous computing and large datasets, bridging the gap between behavior, brain, and computation has the potential to fundamentally transform our understanding of the human mind and inspire the development of truly intelligent artificial agents.
